# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='accountType',
            new_name='role',
        ),
    ]
